export const setRemainingTime = 'setRemainingTime'
export const setGameLink = 'setGameLink'
export const setGameId = 'setGameId'
export const setGame = 'setGame'
export const setBoardOrientation = 'setBoardOrientation'