export const setRemainingTime = 'setRemainingTime'
export const setGameLink = 'setGameLink'
export const setGameId = 'setGameId'
export const setGame = 'setGame'
export const setBoardOrientation = 'setBoardOrientation'
export const setPieceSelection = 'setPieceSelection'
export const setRequestSender = 'setRequestSender'
export const setOpponentDetails = 'setOpponentDetails'