export const setAuthenticated = "setAuthenticated"
export const setSignUpInitialized = "setSignUpInitialized"
export const setShowBottomToast = "setShowBottomToast"
export const setUserDetails = "setUserDetails"
export const setUserFriend =  "setUserFriend"
export const setShowNotification = "setShowNotification"